#服务名称
 server:
   port: 5001

#连接配置信息
 spring:
   application:
     name: config-server-jdbc
   profiles:
     active: jdbc
   cloud:
     config:
       server:
         default-label: dev
         jdbc:
           sql: SELECT akey , avalue FROM config_server where APPLICATION=? and APROFILE=? and LABEL=?
 #####################################################################################################
 # mysql 属性配置
   datasource:
    username: root
    password: 130f89c983ae907f
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://156.226.24.110:3306/config?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
 #####################################################################################################


#指定注册中心地址
 eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:7001/eureka/

